version: '2'
services:
 phpcli:
   build:
     context: docker/phpcli
   working_dir: /var/www
   environment:
     - MS_HOST=manticoresearch-manticore
     - MS_PORT=9308
   volumes:
    - .:/var/www

# Not be used in prod,, highly insecure passwords!
 database:
   image: 'mariadb/server:10.4'
   environment:
     - MARIADB_DATABASE=default
     - MARIADB_USER=docker
     - MARIADB_PASSWORD=docker
     - MARIADB_PORT=3306
     - MARIADB_ROOT_PASSWORD=root


